# Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
# (C.I.: 1.439.390 - Paraguay)

#! /usr/bin/env python
# encoding: utf-8

import wafmod.generators

def options(opt):
    pass

def configure(ctx):
    pass

def build(ctx):
    glob = ctx.GLOBAL

    project = glob.executable()
    project.compilationArg("{target.comp_args}")
    project.includePath("{boost.include}")

    project.archiveLib("chila/connectionTools/lib")
    project.archiveLib("chila/lib/misc")

    project.libPath("{boost.lib}")
    project.lib("boost_system")
    project.targetArg("{target.link_args")    
    
    cpGen = project.addGenerator(wafmod.generators.ConnectionToolsGenerator(srcDir="app/connectors/src", destDir="app/connectors/gen"))
    
    cpGen.addCPerformer("ConnectionPerformer.xml")
    cpGen.addConnector("Network.xml")
    cpGen.addConnector("Logger.xml")
    cpGen.addConnector("MessageProcessor.xml")    

    project.generate()


