# Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
# (C.I.: 1.439.390 - Paraguay)

#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    pass

def configure(ctx):
    pass

def build(ctx):
    glob = ctx.GLOBAL

    project = glob.executable()
    project.compilationArg("{target.comp_args}")

    project.includePath("{boost.include}")
    project.archiveLib("chila/lib/misc")

    project.pkgConfigVars("libxml++-2.6")

    project.libPath("{boost.lib}")
    project.lib("boost_program_options")
    project.lib("boost_filesystem")
    project.lib("boost_system")

    project.installFile('formats.xml')

    project.generate()


