# Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
# (C.I.: 1.439.390 - Paraguay)

#! /usr/bin/env python
# encoding: utf-8

import wafmod.generators

def options(opt):
    pass

def configure(ctx):
    pass

def build(ctx):
    glob = ctx.GLOBAL

    project = glob.sharedLib()
    project.compilationArg("{target.comp_args}")
    project.includePath("{boost.include}")

    project.archiveLib("chila/connectionTools/lib/codegen")
    project.archiveLib("chila/connectionTools/lib/other")
    project.archiveLib("chila/lib/misc")

    project.pkgConfigVars("libxml++")

    project.libPath("{boost.lib}")
    project.lib("boost_program_options")
    project.lib("boost_system")
    project.targetArg("{target.link_args")

    cpGen = project.addGenerator(wafmod.generators.ConnectionToolsGenerator(srcDir="connectors/src", destDir="connectors/gen"))

    cpGen.addCPerformer("ConnectionPerformer.xml")
    cpGen.addConnector("../../../impl/network/connectors/src/Network.xml", True)
    cpGen.addConnector("../../../impl/logger/connectors/src/Logger.xml", True)
    cpGen.addConnector("../../../impl/msgProcessor/connectors/src/MessageProcessor.xml", True)

    project.generate()


