# Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
# (C.I.: 1.439.390 - Paraguay)

#! /usr/bin/env python
# encoding: utf-8

import wafmod.generators

def options(opt):
    pass

def configure(ctx):
    pass

def build(ctx):
    glob = ctx.GLOBAL

    project = glob.executable()
    project.compilationArg("{target.comp_args}")

    project.includePath("{boost.include}")

    project.compilationArg("{qt5.include}")

    project.compilationArg("-DQT_QML_DEBUG")
    project.compilationArg("-DQT_DECLARATIVE_DEBUG")
    project.compilationArg("-DQT_QUICK_LIB")
    project.compilationArg("-DQT_WIDGETS_LIB")
    project.compilationArg("-DQT_GUI_LIB")
    project.compilationArg("-DQT_QML_LIB")
    project.compilationArg("-DQT_NETWORK_LIB")
    project.compilationArg("-DQT_CORE_LIB")

    project.pkgConfigVars("Qt5Widgets")
    project.pkgConfigVars("Qt5Quick")
    project.pkgConfigVars("Qt5Gui")
    project.pkgConfigVars("Qt5Qml")

    project.addGenerator(wafmod.generators.QMLGenerator(
        name="qml",
        rccPath=glob.env["qt5.home"] + "/gcc_64/bin/rcc",
        srcFile="qml.qrc",
        destFile="qml.cpp"))

    project.archiveLib("chila/lib/misc")

    project.libPath("{boost.lib}")

    project.targetArg("{qt5.lib}")

    project.lib("boost_system")

    #project.targetArg("-ccc-gcc-name g++");

    project.generate()


