# Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
# (C.I.: 1.439.390 - Paraguay)

#! /usr/bin/env python
# encoding: utf-8

import wafmod.generators
import os

def options(opt):
    pass

def configure(ctx):
    pass

def build(ctx):
    glob = ctx.GLOBAL

    project = glob.executable()

    project.compilationArg("{target.comp_args}")
    project.pkgConfigVars("libxml++")
    project.pkgConfigVars("gtkmm-2.4")
    project.archiveLib("chila/connectionTools/lib/codegen")
    project.archiveLib("chila/connectionTools/lib/other")
    project.archiveLib("chila/connectionTools/lib/tree")
    project.archiveLib("chila/lib/node")
    project.archiveLib("chila/lib/xmlppUtils")
    project.archiveLib("chila/lib/misc")
    project.includePath("{boost.include}/{boost.version}")
    project.libPath("{boost.lib}/{boost.version}")
    project.lib("boost_program_options{boost.suffix}")
    project.lib("boost_filesystem{boost.suffix}")
    project.lib("boost_system{boost.suffix}")
    project.lib("pthread")
    project.targetArg("{target.link_args}")

    cpGen = project.addGenerator(wafmod.generators.ConnectionToolsGenerator(srcDir="app/connectors/src", destDir="app/connectors/gen"))

    cpGen.addCPerformer("ConnectionPerformer.xml")
    cpGen.addConnector("Logger.xml")
    cpGen.addConnector("FileLoader.xml")
    cpGen.addConnector("MainWindow.xml")

    project.generate()

# test

