/* Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
 * (C.I.: 1.439.390 - Paraguay)
 */

#undef CHILA_LIB_MISC__NSP_FOR
#undef CHILA_LIB_MISC__DEF_NAMESPACE
#undef CHILA_LIB_MISC__DEF_EXCEPTION
#undef CHILA_LIB_MISC__SHOW
#undef CHILA_LIB_MISC__FWDEC_SPTR
#undef CHILA_LIB_MISC__FWDEC_APTR
#undef CHILA_LIB_MISC__FWDEC_TYPE
#undef CHILA_LIB_MISC__DEF_RUNTIME_ERROR
#undef CHILA_LIB_MISC__DEF_EXCEPTION_WB
#undef CHILA_LIB_MISC__CHECK_CALL
#undef CHILA_LIB_MISC__CHECK_CALL_EV
#undef CHILA_LIB_MISC__DEF_RUNTIME_ERROR_WT
