# Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
# (C.I.: 1.439.390 - Paraguay)

#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    pass

def configure(ctx):
    pass

def build(ctx):
    glob = ctx.GLOBAL

    project = glob.archiveLib()
    project.compilationArg("{target.comp_args}")
    project.compilationArg("{libxmlpp.cflags}")
    project.includePath("{boost.include}/{boost.version}")

    project.generate()


