# Copyright 2011-2015 Roberto Daniel Gimenez Gamarra (chilabot@gmail.com)
# (C.I.: 1.439.390 - Paraguay)

#! /usr/bin/env python
# encoding: utf-8

import wafmod.generators


def options(opt):
    pass

def configure(ctx):
    pass

def build(ctx):
    glob = ctx.GLOBAL

    project = glob.archiveLib()
    project.compilationArg("{target.comp_args}")
    project.includePath("{boost.include}/{boost.version}")

#    project.pkgConfigVars("libxml++-2.6")

    cpGen = project.addGenerator(wafmod.generators.ConnectionToolsGenerator(srcDir="common/connectors/src", destDir="common/connectors/gen"))

    cpGen.addConnector("Forwarder.xml")
    cpGen.addConnector("Network.xml")
    cpGen.addConnector("TextMessageCreator.xml")
    cpGen.addConnector("FunDynExecuter.xml")
    cpGen.addConnector("FunDynXMLParser.xml")

    project.generate()


